apiVersion: v1
kind: Service
metadata:
  name: projectcapstone
spec:
  type: NodePort
  selector:
    app: projectcapstone
  ports:
    - nodePort: 30000
      port: 80
      targetPort: 80
      protocol: TCP
