apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectcapstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: projectcapstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: projectcapstone
    spec:
      containers:
        - name: projectcapstone
          image: Sijodevops/projectcapstone
          imagePullPolicy: Always
          ports:
            - containerPort: 80